### ISSUE TITLE
[Bug]: Python UDF Buffer Bug with Limit and Join

### ISSUE THREAD

**Issue by watch2bear** [lovelynewlife/oceanbase#6]
**Describe the bug**

Python UDF Buffer Module is designed for reading data across mulitple blocks.
When SQL contains JOIN opreator and LIMIT Operator, it will occur segement fault with Buffer module.

**Environment**

- OS Version and CPU Arch(`uname -a`):
Centos7 x86_64 

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
OceanBase_CE 4.1.0.1 with Python UDF and buffer for reading across marco blocks.

**Fast Reproduce Steps(Required)**

1. install oceanbase_PyUdf-OB4.1_PyUdf
2. use obclient to connect observer
3. create test table1 and test table 2
4. SQL: select * from test_table1 join test_table2 limit 100

**Expected behavior**

Run SQL and get results correctly

**Actual Behavior**

ERROR 2013 (HY000): Lost connection to MySQL server during query

**Additional context**

Segement Fault in ob_ctype_utf8_os.cc
static void ob_hash_sort_utf8mb4(const ObCharsetInfo *cs, const unsigned char *src, size_t srclen,
               unsigned long int *n1, unsigned long int *n2, const bool calc_end_space, hash_algo hash_algo)
It may be caused by a conflict between the memory management module of oceanbase and the Buffer module.

**Comment by watch2bear** [comment]
SQL and Execution Plan
![image](https://github.com/lovelynewlife/oceanbase/assets/59087106/42a1a113-71ab-4c40-a1ee-695545d7e03d)

Result
![image](https://github.com/lovelynewlife/oceanbase/assets/59087106/c4f1d73a-3940-43a4-8627-4454b32ad477)

Segement Fault
![image](https://github.com/lovelynewlife/oceanbase/assets/59087106/d17e4133-cd17-48b4-b96f-c7868b512ec3)

CALL STACK
![image](https://github.com/lovelynewlife/oceanbase/assets/59087106/cecf1546-d8ad-4701-87ae-79b55d969ad1)

**Comment by lovelynewlife** [comment]
This bug may be due to the misuse of expression evaluation frame in execution context, may be fixed in #8, which handle Model UDF eval in a standalone operator.
